package presentacion;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author deerfox@debian
 */
public class FrmInfoSoporte extends javax.swing.JFrame {

    public void abrirNavegador(String url) {
        try {
            if (Desktop.isDesktopSupported()) {
                // Windows
                Desktop.getDesktop().browse(new URI(url));
            } else {
                // Linux
                Runtime runtime = Runtime.getRuntime();
                runtime.exec("xdg-open " + url);
            }
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form FrmInfoSoporte
     */
    public FrmInfoSoporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblAttribution = new javax.swing.JLabel();
        lblRepo = new javax.swing.JButton();
        lblBack = new javax.swing.JButton();
        lblFA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de EurekaBank Office Manager");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("EurekaBank Office Manager v0.0.1");

        lblCredits.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCredits.setText("Mantenedor de sucursales de un banco que funciona gracias a Java y MySQL.");

        lblAttribution.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblAttribution.setText("Desarrollado por Nícolas Castillo, íconos por: FontAwesome y Material Design Icons.");

        lblRepo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRepo.setText("Reportar un problema");
        lblRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRepoActionPerformed(evt);
            }
        });

        lblBack.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblBack.setText("Volver");
        lblBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBackActionPerformed(evt);
            }
        });

        lblFA.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFA.setText("Info sobre los íconos");
        lblFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRepo)
                        .addGap(49, 49, 49)
                        .addComponent(lblFA)
                        .addGap(60, 60, 60)
                        .addComponent(lblBack))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAttribution)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCredits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCredits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAttribution)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepo)
                    .addComponent(lblFA)
                    .addComponent(lblBack))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRepoActionPerformed
        abrirNavegador("https://github.com/ncr6/eurekabank-examen2/issues");
    }//GEN-LAST:event_lblRepoActionPerformed

    private void lblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_lblBackActionPerformed

    private void lblFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFAActionPerformed
        abrirNavegador("https://fontawesome.com");
    }//GEN-LAST:event_lblFAActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAttribution;
    private javax.swing.JButton lblBack;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JButton lblFA;
    private javax.swing.JButton lblRepo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
